services:
  engine:
    container_name: engine
    build: .
    environment:
      - DATABASE_URL=host=actor-payment port=${DB_PORT} password=${POSTGRES_PASSWORD} user=${POSTGRES_USER} dbname=${POSTGRES_DB} sslmode=disable
    ports:
      - "127.0.0.1:${HOST_PORT_1}:${HOST_PORT_1}"
      - "127.0.0.1:${HOST_PORT_2}:${HOST_PORT_2}"
    depends_on:
      actor-payment:
        condition: service_healthy

  actor-payment:
    container_name: actor-payment
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "127.0.0.1:${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: {}
  go-mod-cache: {}
