// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: msg/messages.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublicPayment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountID     int64                  `protobuf:"varint,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicPayment) Reset() {
	*x = PublicPayment{}
	mi := &file_msg_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicPayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicPayment) ProtoMessage() {}

func (x *PublicPayment) ProtoReflect() protoreflect.Message {
	mi := &file_msg_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicPayment.ProtoReflect.Descriptor instead.
func (*PublicPayment) Descriptor() ([]byte, []int) {
	return file_msg_messages_proto_rawDescGZIP(), []int{0}
}

func (x *PublicPayment) GetAccountID() int64 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *PublicPayment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PrivatePayment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountID     int64                  `protobuf:"varint,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivatePayment) Reset() {
	*x = PrivatePayment{}
	mi := &file_msg_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivatePayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivatePayment) ProtoMessage() {}

func (x *PrivatePayment) ProtoReflect() protoreflect.Message {
	mi := &file_msg_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivatePayment.ProtoReflect.Descriptor instead.
func (*PrivatePayment) Descriptor() ([]byte, []int) {
	return file_msg_messages_proto_rawDescGZIP(), []int{1}
}

func (x *PrivatePayment) GetAccountID() int64 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *PrivatePayment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountID     int64                  `protobuf:"varint,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Period        int32                  `protobuf:"varint,3,opt,name=Period,proto3" json:"Period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_msg_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_msg_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_msg_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Subscription) GetAccountID() int64 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *Subscription) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Subscription) GetPeriod() int32 {
	if x != nil {
		return x.Period
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountID     int64                  `protobuf:"varint,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=Reason,proto3" json:"Reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_msg_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_msg_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_msg_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Error) GetAccountID() int64 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *Error) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_msg_messages_proto protoreflect.FileDescriptor

const file_msg_messages_proto_rawDesc = "" +
	"\n" +
	"\x12msg/messages.proto\"E\n" +
	"\rPublicPayment\x12\x1c\n" +
	"\tAccountID\x18\x01 \x01(\x03R\tAccountID\x12\x16\n" +
	"\x06Amount\x18\x02 \x01(\x01R\x06Amount\"F\n" +
	"\x0ePrivatePayment\x12\x1c\n" +
	"\tAccountID\x18\x01 \x01(\x03R\tAccountID\x12\x16\n" +
	"\x06Amount\x18\x02 \x01(\x01R\x06Amount\"\\\n" +
	"\fSubscription\x12\x1c\n" +
	"\tAccountID\x18\x01 \x01(\x03R\tAccountID\x12\x16\n" +
	"\x06Amount\x18\x02 \x01(\x01R\x06Amount\x12\x16\n" +
	"\x06Period\x18\x03 \x01(\x05R\x06Period\"=\n" +
	"\x05Error\x12\x1c\n" +
	"\tAccountID\x18\x01 \x01(\x03R\tAccountID\x12\x16\n" +
	"\x06Reason\x18\x02 \x01(\tR\x06ReasonB\x1fZ\x1dgithub.com/Ayikoandrew/ap/msgb\x06proto3"

var (
	file_msg_messages_proto_rawDescOnce sync.Once
	file_msg_messages_proto_rawDescData []byte
)

func file_msg_messages_proto_rawDescGZIP() []byte {
	file_msg_messages_proto_rawDescOnce.Do(func() {
		file_msg_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msg_messages_proto_rawDesc), len(file_msg_messages_proto_rawDesc)))
	})
	return file_msg_messages_proto_rawDescData
}

var file_msg_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_msg_messages_proto_goTypes = []any{
	(*PublicPayment)(nil),  // 0: PublicPayment
	(*PrivatePayment)(nil), // 1: PrivatePayment
	(*Subscription)(nil),   // 2: Subscription
	(*Error)(nil),          // 3: Error
}
var file_msg_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msg_messages_proto_init() }
func file_msg_messages_proto_init() {
	if File_msg_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msg_messages_proto_rawDesc), len(file_msg_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_messages_proto_goTypes,
		DependencyIndexes: file_msg_messages_proto_depIdxs,
		MessageInfos:      file_msg_messages_proto_msgTypes,
	}.Build()
	File_msg_messages_proto = out.File
	file_msg_messages_proto_goTypes = nil
	file_msg_messages_proto_depIdxs = nil
}
