// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: storage/payment.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculatePayment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentID     int64                  `protobuf:"varint,1,opt,name=PaymentID,proto3" json:"PaymentID,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=Currency,proto3" json:"Currency,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculatePayment) Reset() {
	*x = CalculatePayment{}
	mi := &file_storage_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePayment) ProtoMessage() {}

func (x *CalculatePayment) ProtoReflect() protoreflect.Message {
	mi := &file_storage_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePayment.ProtoReflect.Descriptor instead.
func (*CalculatePayment) Descriptor() ([]byte, []int) {
	return file_storage_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CalculatePayment) GetPaymentID() int64 {
	if x != nil {
		return x.PaymentID
	}
	return 0
}

func (x *CalculatePayment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CalculatePayment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CalculatePayment) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ProcessPayment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaymentID      int64                  `protobuf:"varint,1,opt,name=PaymentID,proto3" json:"PaymentID,omitempty"`
	InitialPayment float64                `protobuf:"fixed64,2,opt,name=InitialPayment,proto3" json:"InitialPayment,omitempty"`
	ProcessPayment float64                `protobuf:"fixed64,3,opt,name=ProcessPayment,proto3" json:"ProcessPayment,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessPayment) Reset() {
	*x = ProcessPayment{}
	mi := &file_storage_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPayment) ProtoMessage() {}

func (x *ProcessPayment) ProtoReflect() protoreflect.Message {
	mi := &file_storage_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPayment.ProtoReflect.Descriptor instead.
func (*ProcessPayment) Descriptor() ([]byte, []int) {
	return file_storage_payment_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessPayment) GetPaymentID() int64 {
	if x != nil {
		return x.PaymentID
	}
	return 0
}

func (x *ProcessPayment) GetInitialPayment() float64 {
	if x != nil {
		return x.InitialPayment
	}
	return 0
}

func (x *ProcessPayment) GetProcessPayment() float64 {
	if x != nil {
		return x.ProcessPayment
	}
	return 0
}

func (x *ProcessPayment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessPayment) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_storage_payment_proto protoreflect.FileDescriptor

const file_storage_payment_proto_rawDesc = "" +
	"\n" +
	"\x15storage/payment.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x01\n" +
	"\x10CalculatePayment\x12\x1c\n" +
	"\tPaymentID\x18\x01 \x01(\x03R\tPaymentID\x12\x16\n" +
	"\x06Amount\x18\x02 \x01(\x01R\x06Amount\x12\x1a\n" +
	"\bCurrency\x18\x03 \x01(\tR\bCurrency\x128\n" +
	"\tTimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tTimestamp\"\xd0\x01\n" +
	"\x0eProcessPayment\x12\x1c\n" +
	"\tPaymentID\x18\x01 \x01(\x03R\tPaymentID\x12&\n" +
	"\x0eInitialPayment\x18\x02 \x01(\x01R\x0eInitialPayment\x12&\n" +
	"\x0eProcessPayment\x18\x03 \x01(\x01R\x0eProcessPayment\x12\x16\n" +
	"\x06Status\x18\x04 \x01(\tR\x06Status\x128\n" +
	"\tTimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tTimestampB\x1fZ\x1dgithub.com/Ayikoandrew/ap/msgb\x06proto3"

var (
	file_storage_payment_proto_rawDescOnce sync.Once
	file_storage_payment_proto_rawDescData []byte
)

func file_storage_payment_proto_rawDescGZIP() []byte {
	file_storage_payment_proto_rawDescOnce.Do(func() {
		file_storage_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_payment_proto_rawDesc), len(file_storage_payment_proto_rawDesc)))
	})
	return file_storage_payment_proto_rawDescData
}

var file_storage_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_storage_payment_proto_goTypes = []any{
	(*CalculatePayment)(nil),      // 0: CalculatePayment
	(*ProcessPayment)(nil),        // 1: ProcessPayment
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_storage_payment_proto_depIdxs = []int32{
	2, // 0: CalculatePayment.Timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: ProcessPayment.Timestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_storage_payment_proto_init() }
func file_storage_payment_proto_init() {
	if File_storage_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_payment_proto_rawDesc), len(file_storage_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_payment_proto_goTypes,
		DependencyIndexes: file_storage_payment_proto_depIdxs,
		MessageInfos:      file_storage_payment_proto_msgTypes,
	}.Build()
	File_storage_payment_proto = out.File
	file_storage_payment_proto_goTypes = nil
	file_storage_payment_proto_depIdxs = nil
}
